[package]
name = "associated_staking_account"
authors = ["Andrew Fraser<a@serfrae.com>"]
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.10.2"
thiserror = "1.0.30"
